// components/Header.tsx
import type { FunctionComponent } from "preact";

export const Header: FunctionComponent = () => {
  const socialMedia = new Map<string, [string, string]>();

  socialMedia.set("LinkedIn", [
    "\u{f08c}",
    "https://www.linkedin.com/in/jhanviloria/",
  ]);
  socialMedia.set("Twitter", ["\u{f099}", "https://twitter.com/jhanca_vm"]);
  socialMedia.set("GitHub", ["\uf09b", "https://github.com/jhanca-vm"]);

  return (
    <header class="bg-[#f7c28c] py-4 px-5 shadow-sm md:px-8">
      <div class="max-w-5xl mx-auto flex justify-between items-center">
        <span class="text-2xl leading-none font-serif font-semibold">
          Portfolio
        </span>
        <nav>
          <ul class="font-[fa-brands] text-xl flex gap-x-7">
            {[...socialMedia].map(([name, [icon, url]]) => (
              <li key={name}>
                <a
                  class="hover:opacity-80"
                  title={name}
                  href={url}
                  target="_blank"
                  rel="noreferrer"
                >
                  {icon}
                </a>
              </li>
            ))}
          </ul>
        </nav>
      </div>
    </header>
  );
};

// src/lib/Header.svelte
<script>
  import GitHub from './icons/GitHub.svelte'
  import LinkedIn from './icons/LinkedIn.svelte'
  import Twitter from './icons/Twitter.svelte'
</script>

<header
  class="pt-5 flex flex-col gap-y-5 sm:pt-7 sm:flex-row sm:items-center
    sm:justify-between lg:max-w-[62.5rem] lg:mx-auto lg:pt-10"
>
  <p
    class="font-bold text-center text-2xl leading-none tracking-tight
      sm:text-[1.75rem]"
  >
    jhanca-vm
  </p>
  <nav>
    <ul class="flex items-center justify-center gap-x-6 sm:gap-x-8">
      <li>
        <a
          class="hover:text-accent"
          aria-label="GitHub"
          href="https://github.com/jhanca-vm"
          target="_blank"
          rel="noreferrer"
        >
          <GitHub />
        </a>
      </li>
      <li>
        <a
          class="hover:text-accent"
          aria-label="LinkedIn"
          href="https://www.linkedin.com/in/jhanviloria/"
          target="_blank"
          rel="noreferrer"
        >
          <LinkedIn />
        </a>
      </li>
      <li>
        <a
          class="hover:text-accent"
          aria-label="Twitter"
          href="https://twitter.com/jhanca_vm"
          target="_blank"
          rel="noreferrer"
        >
          <Twitter />
        </a>
      </li>
    </ul>
  </nav>
</header>
