// app/components/projects.tsx
import clsx from 'clsx/lite'
import enLaMano from '@/assets/en-la-mano.avif'
import fxChecker from '@/assets/fx-checker.avif'
import healthy from '@/assets/healthy.avif'
import techBookClub from '@/assets/tech-book-club.avif'

const list = [
  [
    'fx_checker',
    'Aplicación web de conversión de divisas.',
    'fx-checker.pages.dev',
    fxChecker
  ],
  [
    'healthy',
    'Sitio web de recetas saludables.',
    'healthy-jvm.vercel.app',
    healthy
  ],
  [
    'en-la-mano',
    'Sitio web para solicitar préstamos en línea.',
    'enlamano.com.uy',
    enLaMano
  ],
  [
    'tech-book-club',
    'Landing page para un club de lectura.',
    'techbookclub.pages.dev',
    techBookClub
  ]
]

export default function Projects() {
  return (
    <section className="py-24 px-6 sm:px-9 md:px-12">
      <div className="max-w-6xl mx-auto">
        <h2
          className={
            'flex items-center gap-9 font-semibold text-2xl md:text-3xl'
          }
        >
          <span>Mis proyectos</span>
          <span className="grow border-t-2 border-dashed border-slate-200" />
        </h2>
        <ul className="mt-12 grid gap-9 md:grid-cols-2">
          {list.map(([id, description, domain, screenshot]) => (
            <li
              className={
                'pt-9 pl-9 flex flex-col rounded-md bg-slate-300/20 lg:pl-12'
              }
              key={id}
            >
              <p
                className={
                  'mr-9 font-medium text-slate-600 text-pretty md:text-lg'
                }
              >
                {description}
              </p>
              <div className="mt-3 mb-9 flex gap-3 font-semibold text-sm">
                <a
                  className="text-blue-600 underline-offset-2 hover:underline"
                  href={`https://${domain}`}
                  target="_blank"
                  rel="noreferrer"
                >
                  Visitar sitio
                </a>
                <a
                  className="text-red-700 underline-offset-2 hover:underline"
                  href={`https://github.com/jhanca-vm/${id}`}
                  target="_blank"
                  rel="noreferrer"
                >
                  Ver código
                </a>
              </div>
              <img
                className={clsx(
                  'mt-auto rounded-tl-md rounded-br-md border-t-3 border-l-3',
                  'border-slate-50'
                )}
                src={screenshot}
                alt=""
                width={580}
                height={413}
                loading="lazy"
              />
            </li>
          ))}
        </ul>
      </div>
    </section>
  )
}

// src/routes/Projects.svelte
<script lang="ts">
  import type { PageData } from './$types'

  export let data: PageData['projects']
</script>

<section class="mb-22 mt-20 sm:mb-24 sm:mt-15 md:mb-28 md:mt-20 lg:mb-32">
  <h2
    class="mb-10 flex items-center gap-x-[1em] text-4xl font-bold
      tracking-tight md:mb-15 md:text-6xl lg:mb-20"
  >
    Projects
    <span class="h-px flex-grow bg-default-100" />
  </h2>
  <div class="grid gap-y-10 sm:grid-cols-2 sm:gap-x-6 lg:gap-x-8">
    {#each data as { id, name, image }}
      <article>
        <img src={image} alt="" width="512" height="320" loading="lazy" />
        <h3 class="mt-5 text-2xl font-bold uppercase">{name}</h3>
        <div class="mt-2 flex gap-x-8 font-medium uppercase tracking-widest">
          <a
            class="link"
            href={`https://${id}-jvm.vercel.app`}
            target="_blank"
            rel="noreferrer"
          >
            View Project
          </a>
          <a
            class="link"
            href={`https://github.com/jhanca-vm/${id}`}
            target="_blank"
            rel="noreferrer"
          >
            View Code
          </a>
        </div>
      </article>
    {/each}
  </div>
</section>
