// src/routes/Footer.svelte
<footer class="-mx-4 bg-default-300 px-4 sm:-mx-8 sm:px-8">
  <div
    class="mx-auto flex max-w-5xl flex-col-reverse items-center gap-y-5 border-t
      border-default-100 pb-10 pt-9 sm:flex-row sm:justify-between"
  >
    <p class="text-[0.9375rem] text-default-200 sm:text-base">
      © Jhan Viloria 2023
    </p>
    <p class="text-[1.0625rem]">
      <strong class="font-semibold">Contact:</strong>
      <a
        class="link"
        href="https://t.me/jhanca"
        target="_blank"
        rel="noreferrer"
      >
        https://t.me/jhanca
      </a>
    </p>
  </div>
</footer>

// components/Footer.tsx
import type { FunctionComponent } from "preact";

export const Footer: FunctionComponent = () => (
  <footer class="px-5 mt-16 sm:mt-20 md:px-8 xl:mt-28">
    <div class="max-w-5xl mx-auto flex items-center justify-between py-6
      border-t border-[#3a2624] border-opacity-50">
      <p class="text-[#3a2624] text-opacity-90">
        <span class="relative top-[0.07rem]">©</span>{" "}
        <span class="text-sm tracking-tight">Jhan Viloria 2022</span>
      </p>
      <a
        class="not-hover:opacity-90"
        href="https://fresh.deno.dev"
        target="_blank"
        rel="noreferrer"
      >
        <img
          class="w-36"
          width="197"
          height="37"
          src="https://fresh.deno.dev/fresh-badge-dark.svg"
          alt="Made with Fresh"
        />
      </a>
    </div>
  </footer>
);
