// src/routes/header.svelte
<script>
  import GitHub from '$lib/icons/github.svelte'
  import LinkedIn from '$lib/icons/linkedin.svelte'
  import Twitter from '$lib/icons/twitter.svelte'

  const socialMedia = [
    { name: 'GitHub', url: 'github.com/jhanca-vm', icon: GitHub },
    {
      name: 'LinkedIn',
      url: 'www.linkedin.com/in/jhanviloria/',
      icon: LinkedIn
    },
    { name: 'Twitter', url: 'twitter.com/jhanca_vm', icon: Twitter }
  ]
</script>

<header
  class="flex flex-col gap-y-5 pt-5 sm:flex-row sm:items-center
    sm:justify-between sm:pt-7 lg:mx-auto lg:max-w-5xl lg:pt-10 xl:pr-8"
>
  <p
    class="text-center text-2xl font-bold leading-none tracking-tight
      sm:text-[1.75rem]"
  >
    jhanca-vm
  </p>
  <nav>
    <ul class="flex items-center justify-center gap-x-6 sm:gap-x-8">
      {#each socialMedia as { name, url, icon }}
        <li>
          <a
            class="transition-colors hover:text-primary"
            aria-label={name}
            href="https://{url}"
            target="_blank"
            rel="noreferrer"
          >
            <svelte:component this={icon} />
          </a>
        </li>
      {/each}
    </ul>
  </nav>
</header>

// components/Header.tsx
import type { FunctionComponent } from "preact";

export const Header: FunctionComponent = () => {
  const socialMedia = new Map<string, [string, string]>();

  socialMedia.set("LinkedIn", [
    "\u{f08c}",
    "https://www.linkedin.com/in/jhanviloria/",
  ]);
  socialMedia.set("Twitter", ["\u{f099}", "https://twitter.com/jhanca_vm"]);
  socialMedia.set("GitHub", ["\uf09b", "https://github.com/jhanca-vm"]);

  return (
    <header class="bg-[#f7c28c] py-4 px-5 shadow-sm md:px-8">
      <div class="max-w-5xl mx-auto flex justify-between items-center">
        <span class="text-2xl leading-none font-serif font-semibold">
          Portfolio
        </span>
        <nav>
          <ul class="font-[fa-brands] text-xl flex gap-x-7">
            {[...socialMedia].map(([name, [icon, url]]) => (
              <li key={name}>
                <a
                  class="hover:opacity-80"
                  title={name}
                  href={url}
                  target="_blank"
                  rel="noreferrer"
                >
                  {icon}
                </a>
              </li>
            ))}
          </ul>
        </nav>
      </div>
    </header>
  );
};
