// src/routes/projects.svelte
<script lang="ts">
  import type { PageData } from './$types'

  export let data: PageData['projects']
</script>

<section class="mb-22 mt-20 sm:mb-24 sm:mt-15 md:mb-28 md:mt-20 lg:mb-32">
  <h2
    class="mb-10 flex items-center gap-x-[1em] text-4xl font-bold
      tracking-tight md:mb-15 md:text-6xl lg:mb-20"
  >
    Projects
    <span class="h-px flex-grow bg-default-100" />
  </h2>
  <div class="grid gap-y-10 sm:grid-cols-2 sm:gap-x-6 lg:gap-x-8">
    {#each data as { id, name, image, url }}
      <article>
        <img
          class="rounded-md"
          src={image}
          alt=""
          width="500"
          height="375"
          loading="lazy"
        />
        <h3 class="mt-5 text-2xl font-bold uppercase">{name}</h3>
        <div class="mt-2 flex gap-x-8 font-medium uppercase tracking-widest">
          <a
            class="link"
            href={`https://${url || `${id}.jhanca-vm.site`}`}
            target="_blank"
            rel="noreferrer"
          >
            View Project
          </a>
          {#if id}
            <a
              class="link"
              href={`https://github.com/jhanca-vm/${id}`}
              target="_blank"
              rel="noreferrer"
            >
              View Code
            </a>
          {/if}
        </div>
      </article>
    {/each}
  </div>
</section>

// components/Projects.tsx
import type { FunctionComponent } from "preact";
import type { Project } from "../types.ts";
import { Section } from "./Section.tsx";

interface Props {
  data: Project[];
}

export const Projects: FunctionComponent<Props> = ({ data }) => (
  <Section title="Projects">
    <div class="grid sm:grid-cols-2 lg:grid-cols-3">
      {data.map(({ name, url, repository, screenshot }) => (
        <div>
          <a href={url} target="_blank" rel="noreferrer">
            <img
              style={{ aspectRatio: "1.6 / 1" }}
              class="w-full rounded shadow-lg border border-gray-100 hover:shadow-2xl"
              src={screenshot}
              alt={name}
              key={name}
            />
          </a>
          <div class="flex items-center justify-between m-2">
            <a href={url} target="_blank" rel="noreferrer">
              <h3 class="font-semibold mt-1 not-hover:opacity-80 hover:text-underline">
                {name}
              </h3>
            </a>
            <a
              class="font-[fa-brands] text-2xl not-hover:opacity-80"
              title="Repository"
              href={repository}
              target="_blank"
              rel="noreferrer"
            >
              &#xf09b;
            </a>
          </div>
        </div>
      ))}
    </div>
  </Section>
);
